export const GET_CUSTOMERS_LOADING = "GET_CUSTOMERS_LOADING"
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS"
export const GET_CUSTOMERS_ERROR = "GET_CUSTOMERS_ERROR"

export const CREATE_CUSTOMER_LOADING = "CREATE_CUSTOMER_LOADING"
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS"
export const CREATE_CUSTOMER_ERROR = "CREATE_CUSTOMER_ERROR"

export const UPDATE_CUSTOMER_LOADING = "UPDATE_CUSTOMER_LOADING"
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS"
export const UPDATE_CUSTOMER_ERROR = "UPDATE_CUSTOMER_ERROR"

export const DELETE_CUSTOMER_LOADING = "DELETE_CUSTOMER_LOADING"
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS"
export const DELETE_CUSTOMER_ERROR = "DELETE_CUSTOMER_ERROR"
