export const GET_EMPLOYEES_LOADING = "GET_EMPLOYEES_LOADING"
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS"
export const GET_EMPLOYEES_ERROR = "GET_EMPLOYEES_ERROR"

export const CREATE_EMPLOYEE_LOADING = "CREATE_EMPLOYEE_LOADING"
export const CREATE_EMPLOYEE_SUCCESS = "CREATE_EMPLOYEE_SUCCESS"
export const CREATE_EMPLOYEE_ERROR = "CREATE_EMPLOYEE_ERROR"

export const UPDATE_EMPLOYEE_LOADING = "UPDATE_EMPLOYEE_LOADING"
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS"
export const UPDATE_EMPLOYEE_ERROR = "UPDATE_EMPLOYEE_ERROR"

export const DELETE_EMPLOYEE_LOADING = "DELETE_EMPLOYEE_LOADING"
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS"
export const DELETE_EMPLOYEE_ERROR = "DELETE_EMPLOYEE_ERROR"
